version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
    REPONAME: "notejam"
    TAG: "latest"
phases:
  pre_build:
    commands:
      # - echo Logging in to DockerHub...
      # - docker login -u eirriel -p $BUILD_TOKEN
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Pulling secrets
      - echo "ENVIRONMENT=production" > notejam/.env
      - echo "SQLALCHEMY_DATABASE_URI=$(aws secretsmanager get-secret-value --secret-id db_credentials --query SecretString --output text)" >> notejam/.env
      - echo Building the Docker image...          
      - cd notejam && docker build -t $REPONAME:$TAG . && cd ..
      - docker tag $REPONAME:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPONAME:$TAG 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPONAME:$TAG
      - printf '{"ImageURI":"%s"}' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPONAME:$TAG  > imageDetail.json
      - cp -vf notejam/container_def_template.json container_def.json
      - sed -i 's/<TASK_DEFINITION>/'$TASK_DEFINITION'/g' appspec.yml
      - sed -i 's/<APP_NAME>/'$REPONAME'/g' appspec.yml container_def.json
      - sed -i 's/<SERVICE_PORT>/'$SERVICE_PORT'/g' appspec.yml container_def.json
      - sed -i 's/<AWS_ACCOUNT_ID>/'$AWS_ACCOUNT_ID'/g' container_def.json
      - sed -i 's/<IMAGE_NAME>/'$AWS_ACCOUNT_ID'\.dkr\.ecr\.'$AWS_DEFAULT_REGION'\.amazonaws.com\/'$REPONAME'\:'$TAG'/g' container_def.json
      - cat container_def.json
      - aws s3 cp container_def.json s3://notejam-codepipeline-artifacts/debug/
artifacts:
  files: 
    - imageDetail.json
    - appspec.yml
    - container_def.json